"""empty message

Revision ID: 0d254266b491
Revises: c1584219ea62
Create Date: 2024-10-02 22:52:49.253196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d254266b491'
down_revision = 'c1584219ea62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('interest_types')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_types', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
