"""empty message

Revision ID: 4e276a0aedc3
Revises: b092352b3df6
Create Date: 2024-10-02 14:39:46.349850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e276a0aedc3'
down_revision = 'b092352b3df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('current_location', sa.Text(), nullable=True),
    sa.Column('hometown', sa.Text(), nullable=True),
    sa.Column('college', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('education_level', sa.Enum('NO_FORMAL_EDUCATION', 'PRIMARY_SCHOOL', 'SECONDARY_SCHOOL', 'UNDERGRAD', 'POSTGRAD', 'PHD', 'PREFER_NOT_TO_SAY', name='educationlevelenum'), nullable=True),
    sa.Column('mbti', sa.Enum('INTJ', 'INTP', 'ENTJ', 'ENTP', 'INFJ', 'INFP', 'ENFJ', 'ENFP', 'ISTJ', 'ISFJ', 'ESTJ', 'ESFJ', 'ISTP', 'ISFP', 'ESTP', 'ESFP', 'PREFER_NOT_TO_SAY', name='mbtienum'), nullable=True),
    sa.Column('constellation', sa.Enum('ARIES', 'TAURUS', 'GEMINI', 'CANCER', 'LEO', 'VIRGO', 'LIBRA', 'SCORPIO', 'SAGITTARIUS', 'CAPRICORN', 'AQUARIUS', 'PISCES', 'PREFER_NOT_TO_SAY', name='constellationenum'), nullable=True),
    sa.Column('blood_type', sa.Enum('A', 'B', 'AB', 'O', 'OTHER', 'PREFER_NOT_TO_SAY', name='bloodtypeenum'), nullable=True),
    sa.Column('religion', sa.Enum('AGNOSTIC', 'ATHEIST', 'BUDDHIST', 'CATHOLIC', 'CHRISTIAN', 'HINDU', 'JEWISH', 'MUSLIM', 'SIKH', 'SPIRITUAL', 'ORTHODOX_CHRISTIAN', 'PROTESTANT', 'SHINTO', 'TAOIST', 'OTHER', 'PREFER_NOT_TO_SAY', name='religionenum'), nullable=True),
    sa.Column('sexuality', sa.Enum('STRAIGHT', 'GAY', 'LESBIAN', 'BISEXUAL', 'ASEXUAL', 'PANSEXUAL', 'QUEER', 'QUESTIONING', 'NOT_LISTED', 'PREFER_NOT_TO_SAY', name='sexualityenum'), nullable=True),
    sa.Column('ethnicity', sa.Enum('BLACK_AFRICAN_DESCENT', 'EAST_ASIAN', 'SOUTH_ASIAN', 'SOUTHEAST_ASIAN', 'HISPANIC_LATINO', 'MIDDLE_EASTERN_NORTH_AFRICAN', 'NATIVE_AMERICAN_INDIGENOUS', 'PACIFIC_ISLANDER', 'WHITE_CAUCASIAN', 'MULTIRACIAL', 'OTHER', 'PREFER_NOT_TO_SAY', name='ethnicityenum'), nullable=True),
    sa.Column('diet', sa.Enum('OMNIVORE', 'VEGETARIAN', 'VEGAN', 'PESCATARIAN', 'KETOGENIC', 'PALEO', 'OTHER', 'PREFER_NOT_TO_SAY', name='dietenum'), nullable=True),
    sa.Column('smoke', sa.Integer(), nullable=True),
    sa.Column('drinking', sa.Integer(), nullable=True),
    sa.Column('marijuana', sa.Integer(), nullable=True),
    sa.Column('drugs', sa.Integer(), nullable=True),
    sa.Column('skills', sa.PickleType(), nullable=True),
    sa.Column('personalities', sa.PickleType(), nullable=True),
    sa.Column('languages', sa.PickleType(), nullable=True),
    sa.Column('interest_types', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
