"""empty message

Revision ID: 980da8f015ec
Revises: 65b32b5b39d2
Create Date: 2024-11-25 19:29:18.279641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980da8f015ec'
down_revision = '65b32b5b39d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_post_id', ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_post_id')

    # ### end Alembic commands ###
