"""empty message

Revision ID: c1584219ea62
Revises: bd7d5a4c2d06
Create Date: 2024-10-02 21:12:36.060988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1584219ea62'
down_revision = 'bd7d5a4c2d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('comment_created_date', sa.DateTime(), nullable=False),
    sa.Column('comment_last_updated_date', sa.DateTime(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_applicants',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('applied_time', sa.DateTime(), nullable=False),
    sa.Column('review_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('post_bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('post_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('comment_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_last_updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('event_start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('event_end_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('number_of_people_required', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('skills', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('personalities', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('interest_types', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('attributes', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('attributes')
        batch_op.drop_column('interest_types')
        batch_op.drop_column('languages')
        batch_op.drop_column('personalities')
        batch_op.drop_column('skills')
        batch_op.drop_column('location')
        batch_op.drop_column('number_of_people_required')
        batch_op.drop_column('event_end_date')
        batch_op.drop_column('event_start_date')
        batch_op.drop_column('post_last_updated_date')

    op.drop_table('comment_likes')
    op.drop_table('post_likes')
    op.drop_table('post_bookmarks')
    op.drop_table('post_applicants')
    op.drop_table('comments')
    # ### end Alembic commands ###
