"""empty message

Revision ID: d1c05a8d0595
Revises: 0be5e6a57d9c
Create Date: 2024-12-16 15:55:09.674997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c05a8d0595'
down_revision = '0be5e6a57d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
